services:
  - type: web
    name: gym-app-bot
    env: python
    pythonVersion: "3.11"
    plan: free
    buildCommand: pip install --upgrade pip && pip install --only-binary :all: -r requirements.txt || pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: USE_WEBHOOK
        value: "false"
      - key: PORT
        fromService:
          type: web
          name: gym-app-bot
          property: port

